### ISSUE TITLE
Failing deployment after latest changes

### ISSUE THREAD

**Issue by simoneb** [nearform/optic#238]
See https://github.com/nearform/optic/actions/runs/4173619239

**Comment by francardoso93** [comment]
- Fixed id-token permission
- Fixed secret value for identity provider
- Working on: Required permission in GCP for service account + federation

**Comment by francardoso93** [comment]
I'm suggesting some future project improvements, as this issue required a lot of manual work on the GCP side:

Overall:
- Segregate GCP project per environment (Resource isolation, more secure)

Terraform:
- Start using remote backend
- Add missing resources to terraform (IAM role binding for service account, WIF...)
- Consider adopting Terraspace or Terragrunt to make multiple env management easier
- Create the first secret version (otherwise workflow will fail due to "not found or has no versions."). Also remember to add suffix "-dev" to secretNames

**Comment by simoneb** [comment]
@francardoso93 where do we stand with this one?

**Comment by francardoso93** [comment]
This was fixed :heavy_check_mark: 
Please check the "Before approving/merging" description section in the PR.
