### ISSUE TITLE
Notifications are not being sent

### ISSUE THREAD

**Issue by simoneb** [nearform/optic#615]
See https://github.com/nearform/fast-jwt/actions/runs/10722520440.

The issue seems to be in the push notifications to mobile which are not being sent, or received by the mobile phone.

**Comment by kieranswhite** [comment]
@bencoder and I spent some time looking into this today. From looking into things it looks like that the pipeline is failing because the Optic Expo app (and Nearform org) have been removed from the Google Play Store (https://play.google.com/store/apps/details?id=com.nearform.optic). Ben managed to confirm push notifications worked using SDK47 of expo go (download [here](https://expo.dev/go)) and installing Optic there. The interim solution is to sideload Expo go SDK 47 and install the Optic Expo app there. We may not even re-activate the app/Organisation which @simoneb is going to look into.

**Comment by simoneb** [comment]
Just to confirm what I did, the "solution" was to go back to using the Expo Go version of the app, by installing a version of Expo Go compatible with SDK 47. The notifications on the Play Store version no longer work, likely due to the Google account having been closed due to inactivity, hence the app delisted from the store.
